export const REQUEST_GET_READINGS = 'REQUEST_GET_READINGS';
export const REQUEST_GET_READINGS_SUCCESS = 'REQUEST_GET_READINGS_SUCCESS';
export const REQUEST_GET_READINGS_FAILURE = 'REQUEST_GET_READINGS_FAILURE';

export const REQUEST_SET_READINGS = 'REQUEST_SET_READINGS_STATUS';
